### ISSUE TITLE
update Fermipy 

### ISSUE THREAD

**Issue by grburgess** [fermi-lat/FermiBottle#14]
this is in reference to https://github.com/fermiPy/fermipy/issues/515#issuecomment-1396106396. 
Fermipy should be updated to 1.2.0 to fix an issues with the numpy version causing errors in irf.py

**Comment by Areustle** [comment]
Should be addressed by https://github.com/fermi-lat/FermiBottle/commit/69b39e381da011a2e22abb36e990bf8dc8e64a9c , along with an update to ds9.

**Comment by Areustle** [comment]
@grburgess This morning I uploaded both x86 and ARM versions of the new fermibottle with the fermipy updates to dockerhub. https://hub.docker.com/r/fssc/fermibottle/tags
