### ISSUE TITLE
tempo2 - missing fermi plugin?

### ISSUE THREAD

**Issue by jleagle94** [fermi-lat/FermiBottle#15]
Hi, 

I think the fermi plugin is missing for Tempo2 in the fermibottle docker container. I've tried running:
`!tempo2 -gr fermi -h`
and get the error:
`Looking for /home/fermi/astrosoft/tempo2/T2runtime/plugins//fermi_linux-gnu_plug.t2
dlerror() = /home/fermi/astrosoft/tempo2/T2runtime/plugins//fermi_linux-gnu_plug.t2: cannot open shared object file: No such file or directory
[error]: dlopen() failed while resolving symbols.`

Indeed the directory does not exist.

**Comment by jleagle94** [comment]
I have heard of other Docker users having the same issue. One Docker user reports they had to create a new conda environment without the Fermitools for the Tempo2 to install with all plugins including the fermi plugin to work properly. There is another alternative that is easier.

There is a Python package that does what tempo2 fermi plugin does called pint-pulsar: https://github.com/nanograv/PINT

You can easily install it in the Fermi conda environment and it does the same thing as Tempo2: https://nanograv-pint.readthedocs.io/en/latest/tutorials.html

Another added benefit is the fermiphase is already in the Python package itself (no additional plugins or even the Fermitools are required to run this). https://nanograv-pint.readthedocs.io/en/stable/command-line.html#fermiphase

Hope this helps anyone else while we track down the issue.

**Comment by Areustle** [comment]
When building it's own plugin code with the more modern version of gcc that FermiBottle now uses, Tempo2 itself threw a compiler error. Upgrading to a more recent version of tempo2 (2021.6.1) resolved the issue. The most recent code has be committed to the main branch, and the images for x86 and arm have been regenerated. They are available at dockerhub under tags 23.03.10.0.amd64, and 23.03.10.0.arm64 respectively. Downloading the latest tag will also get the appropriate one for your machine.
