### ISSUE TITLE
tempo2 fermi plugin failure

### ISSUE THREAD

**Issue by Areustle** [fermi-lat/FermiBottle#4]
Samayra Straal reported an issue with the tempo2 fermi plugin not working in the current fermi bottle. Attempts to run the tool throw a library not found error for libpgplot.so, and libcfitsio.so.5

Linking should occur against the libraries in /opt/anaconda/. should be added as RPATH into the compiled executable for tempo2, or other solution that does not require using LD_LIBRARY_PATH.

**Comment by joeastro** [comment]
I encountered this issue with my own testing. My workaround was to add a directory to the LD_LIBRARY_PATH by adding the following line in the ~/.bashrc file:

`LD_LIBRARY_PATH=/home/astrosoft/pgplot/:$LD_LIBRARY_PATH`

This allowed the rest of the PulsarGating analysis thread to be run successfully.

**Comment by donhorner** [comment]
Should we just add this workaround to the FermiBottle [Troubleshooting page](https://github.com/fermi-lat/FermiBottle/wiki/Troubleshooting)?
