### ISSUE TITLE
Does not build due to no longer existing ds9 version

### ISSUE THREAD

**Issue by IevgenVovk** [fermi-lat/FermiBottle#5]
**Problem:** building of the docker container fails
**Steps to reproduce:** docker build .
**Systems:** Ubuntu 19.10 (the problem should be platform-independent)

Container building fails downloading the DS9 release tar.gz:
```
Step 23/44 : RUN mkdir $ASTROPFX/bin && cd $ASTROPFX/bin && curl http://ds9.si.edu/download/centos6/ds9.centos6.8.0.tar.gz | tar zxv
 ---> Running in b5a58d34de2a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
104   313  104   313    0     0    349      0 --:--:-- --:--:-- --:--:--   634

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir $ASTROPFX/bin && cd $ASTROPFX/bin && curl http://ds9.si.edu/download/centos6/ds9.centos6.8.0.tar.gz | tar zxv' returned a non-zero code: 2
```

Checking the corresponding [website](http://ds9.si.edu/download/centos6/), one can see that the 6.8.0 version is no longer there; presumably it is replaced with 6.8.1. Replacing the 
`curl http://ds9.si.edu/download/centos6/ds9.centos6.8.0.tar.gz | tar zxv` 
command with 
`curl http://ds9.si.edu/download/centos6/ds9.centos6.8.1.tar.gz | tar zxv`
in the Dockerfile solves the issue.

**Comment by IevgenVovk** [comment]
The proposed fix is implemented in the pull request #6 .

**Comment by jasercion** [comment]
@Areustle Please verify fix in PR and issue merge decision

**Comment by Areustle** [comment]
Solved by PR
