### ISSUE TITLE
conda activate py3 doesn't work

### ISSUE THREAD

**Issue by mfacorcoran** [fermi-lat/FermiBottle#7]
"conda activate py3" (as described in the usage instructions) gives me an error:

<pre>
[gs66-seagull:~/fermibottle] % docker ps -a
CONTAINER ID   IMAGE              COMMAND                  CREATED         STATUS    PORTS     NAMES
172809aa2aaa   fssc/fermibottle   "/opt/docker/bin/ent…"   9 seconds ago   Created             modest_snyder
[gs66-seagull:~/fermibottle] mcorcora% docker start modest_snyder
modest_snyder
[gs66-seagull:~/fermibottle] % docker attach modest_snyder
(base) [fermi@172809aa2aaa ~]$ conda activate py3
Could not find conda environment: py3
</pre>

**Comment by donhorner** [comment]
I think the correct environment name is "gbm".  @Areustle can you check and update the documentation?

**Comment by donhorner** [comment]
Another question for @Areustle.  Are the GBM data tools installed in the container or just gspec?  We should have them on there.  See [https://fermi.gsfc.nasa.gov/ssc/data/analysis/gbm/](https://fermi.gsfc.nasa.gov/ssc/data/analysis/gbm/) for the data tools package, if needed.

**Comment by Areustle** [comment]
They gbm data tools are now installed, along with gspec. I've changed the environment name to `gspec` since the gbm_data_tools fit better in the fermi environment.
