### ISSUE TITLE
.config directory not writeable

### ISSUE THREAD

**Issue by mfacorcoran** [fermi-lat/FermiBottle#8]
I issued the command ``%matplotlib inline`` in a notebook and got the following warning:

<pre>
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-82q00dwz because the default path (/home/fermi/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
</pre>

indeed ``/home/fermi/.config`` is owned by root so is not writeable; should it be?

**Comment by Areustle** [comment]
Fixed via https://github.com/fermi-lat/FermiBottle/blob/80f6306d9c82bee26b16a1e9c14e2df025b253ba/docker/entrypoint#L35
