### ISSUE TITLE
heasoft 6.28 vs. 6.24

### ISSUE THREAD

**Issue by mfacorcoran** [fermi-lat/FermiBottle#9]
the heasoft version in fermibottle is 6.24, while the latest release is 6.28

<pre>
(base) [fermi@172809aa2aaa data]$ fversion
24Apr2018_V6.24
</pre>

Can heasoft be updated in the container?  or can the user update it themselves (if so how)?

**Comment by Areustle** [comment]
The version of gcc available in the centos7 docker base container is 4.8.5, which is too old to compile 6.28. I have however compiled heasoft 6.26 with it, and included that in the latest dev tag.
